# Exercise 2: numpy

In [1]:
import numpy as np

## Problem 1: 

Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **matrix** objects

In [15]:
################
# your solution
################

A = np.matrix([[3,2,1],[6,-3,0],[1,2,9]])
print (A,'\n')
B = np.matrix([[-4,1],[7,3],[2,5]])
print(B,'\n')
C = A*B

print(C)

[[ 3  2  1]
 [ 6 -3  0]
 [ 1  2  9]] 

[[-4  1]
 [ 7  3]
 [ 2  5]] 

[[  4  14]
 [-45  -3]
 [ 28  52]]


Compute
$$
   \left[ \begin{array}{ccc}
   3 &  2 & 1 \\
   6 & -3 & 0 \\
   1 &  2 & 9 \\
   \end{array} \right]
   \left[ \begin{array}{ccc}
   -4 & 1 \\
    7 & 3 \\
    2 & 5 \\
   \end{array} \right]
$$
using **array** objects

In [16]:
D = np.array([[3,2,1],[6,-3,0],[1,2,9]])
E = np.array([[-4,1],[7,3],[2,5]])
F = D@E

print(F)

[[  4  14]
 [-45  -3]
 [ 28  52]]


## Problem 2: 

Numpy provides random number generators for different distributions.
You can find simple examples at [https://numpy.org/doc/stable/reference/random/index.html](https://numpy.org/doc/stable/reference/random/index.html)

1. Write a function that outputs a list of 250 numbers in a normal distribution with (approximately) mean of 2.5 and standard deviation of 0.75. (check [https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy.random.normal))
2. Write a loop that uses this function to create 10 instances of such lists. Compute the actual mean and standard deviation and print them.
3. Verify that the answers are indeed random by running your code multiple times.

In [53]:
################
# your solution
################
# mean and standered deviation
mu, sigma = 2.5,0.75

for i in range(10):
    s = np.random.normal(mu, sigma, 250)
    #mean = np.mean(s)
    #std = np.std(s, ddof =1)
    print ('instance {} \n mean = {}   standered deviation = {} \n'.format(i+1,np.mean(s),np.std(s, ddof =1)) )
    #a = np.vstack([a,s])

instance 1 
 mean = 2.4825702052198486   standered deviation = 0.6984266620167159 

instance 2 
 mean = 2.484880441229045   standered deviation = 0.7493075793233172 

instance 3 
 mean = 2.529161497313059   standered deviation = 0.706191714917457 

instance 4 
 mean = 2.517468169225472   standered deviation = 0.6918856068798991 

instance 5 
 mean = 2.537890564388952   standered deviation = 0.7031836264333823 

instance 6 
 mean = 2.47424786915957   standered deviation = 0.8124950410499672 

instance 7 
 mean = 2.537107047720678   standered deviation = 0.7399675943612871 

instance 8 
 mean = 2.4969244683013323   standered deviation = 0.763201840649985 

instance 9 
 mean = 2.5510487910359547   standered deviation = 0.702975121942357 

instance 10 
 mean = 2.4563231246581947   standered deviation = 0.7429512773651358 



## Problem 3: 

1. Compute and print the eigenvalues, $\lambda_i$, and eigenvectors, ${\bf n}_i$, of
$$
   {\bf A} =
   \left[ \begin{array}{ccccc}
   3 & 2 & 1 & 0 & 0 \\
   2 & 3 & 2 & 1 & 0 \\
   1 & 2 & 3 & 2 & 1 \\
   0 & 1 & 2 & 3 & 2 \\
   0 & 0 & 1 & 2 & 3 
   \end{array} \right]
$$
2. Show that
$$
   {\rm det}({\bf A}) = \prod_{i=1}^5 \lambda_i
$$
3. Verify the following relation
$$
   {\bf A} = \sum_{i=1}^{5} \lambda_i\,{\bf n}_i\otimes{\bf n}_i
$$

In [55]:
################
# your solution
################
A = np.array([[3,2,1,0,0],[2,3,2,1,0],[1,2,3,2,1],[0,1,2,3,2],[0,0,1,2,3]])
(lam,vec)=np.linalg.eig(A)
print(lam,'\n')
print(vec,'\n')




[7.65427349 4.56155281 1.74770274 0.43844719 0.59802377] 

[[ 3.28733703e-01  5.57345410e-01  6.17548407e-01  4.35162146e-01
   1.02801351e-01]
 [ 4.85676469e-01  4.35162146e-01 -1.78297793e-01 -5.57345410e-01
  -4.82004424e-01]
 [ 5.58663621e-01 -1.71558655e-16 -4.16758592e-01 -2.00458955e-15
   7.17082447e-01]
 [ 4.85676469e-01 -4.35162146e-01 -1.78297793e-01  5.57345410e-01
  -4.82004424e-01]
 [ 3.28733703e-01 -5.57345410e-01  6.17548407e-01 -4.35162146e-01
   1.02801351e-01]] 



In [57]:
sum = 1
for i in lam:
    sum *= i

print(sum,np.linalg.det(A))
    
if np.linalg.det(A) == sum:
    print ("det(A) = summation of eigen values")


15.999999999999993 15.999999999999991


In [58]:
x = np.zeros(shape=(5,5))
for i in range(5):
    y = lam[i]*np.outer(vec[:,i],vec[:,i])
    x += y

print (x)

[[3.00000000e+00 2.00000000e+00 1.00000000e+00 1.17961196e-16
  6.96491476e-16]
 [2.00000000e+00 3.00000000e+00 2.00000000e+00 1.00000000e+00
  9.02056208e-16]
 [1.00000000e+00 2.00000000e+00 3.00000000e+00 2.00000000e+00
  1.00000000e+00]
 [1.17961196e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00
  2.00000000e+00]
 [6.96491476e-16 9.02056208e-16 1.00000000e+00 2.00000000e+00
  3.00000000e+00]]
